services:
  # pacientewebapi:
  #   image: ${DOCKER_REGISTRY-}pacientewebapi
  #   build:
  #     context: .
  #     dockerfile: PacienteWebApi/Dockerfile
  #   ports:
  #     - 5000:8080
  #     - 5001:8081
  #   container_name: PacienteWebApi_container
  #   depends_on:
  #     sqlserver:
  #       condition: service_healthy

  # citasmedicaswebapi:
  #   image: ${DOCKER_REGISTRY-}citasmedicaswebapi
  #   build:
  #     context: .
  #     dockerfile: CitaMedicaWebApi/Dockerfile
  #   ports:
  #     - 5002:8080
  #     - 5003:8081
  #   container_name: CitasMedicasWebApi_container
  #   depends_on:
  #     sqlserver:
  #       condition: service_healthy

  # historiaclinicawebapi:
  #   image: ${DOCKER_REGISTRY-}historiaclinicawebapi
  #   build:
  #     context: .
  #     dockerfile: HistoriaClinicaWebApi/Dockerfile
  #   ports:
  #     - 5004:8080
  #     - 5005:8081
  #   container_name: HistoriaClinicaWebApi_container
  #   depends_on:
  #     sqlserver:
  #       condition: service_healthy

  # authwebapi:
  #   image: ${DOCKER_REGISTRY-}authwebapi
  #   build:
  #     context: .
  #     dockerfile: AuthWebApi/Dockerfile
  #   ports:
  #     - 5006:8080
  #     - 5007:8081
  #   container_name: AuthWebApi_container
  #   depends_on:
  #     sqlserver:
  #       condition: service_healthy

  administrativowebapi:
    image: ${DOCKER_REGISTRY-}administrativowebapi
    build:
      context: .
      dockerfile: AdministrativoWebApi/Dockerfile
    ports:
      - 5008:8080
      - 5009:8081
    container_name: AdministrativoWebApi_container
    depends_on:
      sqlserver:
        condition: service_healthy

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Abc*123!
      - ACCEPT_EULA=Y
    volumes:
      - sqlserver-data:/var/opt/mssql
    container_name: SQLServer_container
    healthcheck:
      test: ["CMD", "echo", "SQL Server is running"]
      interval: 1s
      timeout: 10s
      retries: 1

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "443:443"
    volumes:
      - ./ssl/server.crt:/etc/nginx/certs/server.crt
      - ./ssl/server.key:/etc/nginx/certs/server.key
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      # - citasmedicaswebapi
      # - pacientewebapi
      # - historiaclinicawebapi
      - administrativowebapi

  frontenda:
    image: ${DOCKER_REGISTRY-}frontenda
    build:
      context: ./frontAdmin
      dockerfile: Dockerfile  
    ports:
      - "5010:446"
    volumes:
      - ./frontAdmin/ssl/server.crt:/etc/nginx/certs/server.crt
      - ./frontAdmin/ssl/server.key:/etc/nginx/certs/server.key
      - ./frontAdmin/ssl/nginx-default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      # - pacientewebapi
      # - citasmedicaswebapi
      # - historiaclinicawebapi
      - administrativowebapi
  
  # frontendm:
  #   image: ${DOCKER_REGISTRY-}frontendm
  #   build:
  #     context: ./frontMedico
  #     dockerfile: Dockerfile  
  #   ports:
  #     - "5011:444"
  #   volumes:
  #     - ./frontMedico/ssl/server.crt:/etc/nginx/certs/server.crt
  #     - ./frontMedico/ssl/server.key:/etc/nginx/certs/server.key
  #     - ./frontMedico/ssl/nginx-default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - pacientewebapi
  #     - citasmedicaswebapi
  #     - historiaclinicawebapi
  #     - administrativowebapi
  
  # frontendc:
  #   image: ${DOCKER_REGISTRY-}frontendc
  #   build:
  #     context: ./frontCliente
  #     dockerfile: Dockerfile  
  #   ports:
  #     - "5012:445"
  #   volumes:
  #     - ./frontCliente/ssl/server.crt:/etc/nginx/certs/server.crt
  #     - ./frontCliente/ssl/server.key:/etc/nginx/certs/server.key
  #     - ./frontCliente/ssl/nginx-default.conf:/etc/nginx/conf.d/default.conf
  #   depends_on:
  #     - pacientewebapi
  #     - citasmedicaswebapi
  #     - historiaclinicawebapi
  #     - administrativowebapi

volumes:
  sqlserver-data:
