version: '3.8'

services:
  pacientewebapi:
    image: mangas330/pacientewebapi
    ports:
    - target: 8080
      published: 4999
      protocol: tcp
      mode: ingress
    - target: 8081
      published: 5001
      protocol: tcp
      mode: ingress
    environment:
      - aspnetcore_environment=development
      - AES_KEY=${AES_KEY}
      - AES_IV=${AES_IV}
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    networks:
      - HCE_app-network

  citasmedicaswebapi:
    image: mangas330/citasmedicaswebapi
    ports:
    - target: 8080
      published: 5002
      protocol: tcp
      mode: ingress
    - target: 8081
      published: 5003
      protocol: tcp
      mode: ingress
    environment:
      - aspnetcore_environment=development
      - AES_KEY=${AES_KEY}
      - AES_IV=${AES_IV}
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    networks:
      - HCE_app-network

  historiaclinicawebapi:
    image: mangas330/historiaclinicawebapi
    ports:
    - target: 8080
      published: 5004
      protocol: tcp
      mode: ingress
    - target: 8081
      published: 5005
      protocol: tcp
      mode: ingress
    environment:
      - aspnetcore_environment=development
      - AES_KEY=${AES_KEY}
      - AES_IV=${AES_IV}
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    networks:
      - HCE_app-network

  authwebapi:
    image: mangas330/authwebapi
    ports:
    - target: 8080
      published: 5006
      protocol: tcp
      mode: ingress
    - target: 8081
      published: 5007
      protocol: tcp
      mode: ingress
    environment:
      - aspnetcore_environment=development
      - AES_KEY=${AES_KEY}
      - AES_IV=${AES_IV}
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    networks:
      - HCE_app-network

  administrativowebapi:
    image: mangas330/administrativowebapi
    ports:
    - target: 8080
      published: 5008
      protocol: tcp
      mode: ingress
    - target: 8081
      published: 5009
      protocol: tcp
      mode: ingress
    environment:
      - aspnetcore_environment=development
      - AES_KEY=${AES_KEY}
      - AES_IV=${AES_IV}
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    networks:
      - HCE_app-network

  facturacion-automatica:
    image: mangas330/administrativowebapi
    entrypoint: ["dotnet", "AdministrativoWebApi.dll", "--facturacion"] # Modificá el entrypoint para correr solo la facturación
    environment:
      - aspnetcore_environment=development
      - AES_KEY=${AES_KEY}
      - AES_IV=${AES_IV}
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    networks:
      - HCE_app-network

networks:
  HCE_app-network:
    external: true
