version: '3.8'

services:
  nginx:
    image: mangas330/nginx
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    volumes:
      - ./ssl/server.crt:/etc/nginx/certs/server.crt
      - ./ssl/server.key:/etc/nginx/certs/server.key
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    networks:
      - app-network

  pacientewebapi:
    image: mangas330/pacientewebapi
    ports:
    - target: 8080
      published: 4999
      protocol: tcp
      mode: ingress
    - target: 8081
      published: 5001
      protocol: tcp
      mode: ingress
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    networks:
      - app-network

  citasmedicaswebapi:
    image: mangas330/citasmedicaswebapi
    ports:
    - target: 8080
      published: 5002
      protocol: tcp
      mode: ingress
    - target: 8081
      published: 5003
      protocol: tcp
      mode: ingress
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    networks:
      - app-network

  historiaclinicawebapi:
    image: mangas330/historiaclinicawebapi
    ports:
    - target: 8080
      published: 5004
      protocol: tcp
      mode: ingress
    - target: 8081
      published: 5005
      protocol: tcp
      mode: ingress
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    networks:
      - app-network

  authwebapi:
    image: mangas330/authwebapi
    ports:
    - target: 8080
      published: 5006
      protocol: tcp
      mode: ingress
    - target: 8081
      published: 5007
      protocol: tcp
      mode: ingress
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    networks:
      - app-network

  administrativowebapi:
    image: mangas330/administrativowebapi
    ports:
    - target: 8080
      published: 5008
      protocol: tcp
      mode: ingress
    - target: 8081
      published: 5009
      protocol: tcp
      mode: ingress
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    networks:
      - app-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
    - target: 1433
      published: 1433
      protocol: tcp
      mode: ingress
    environment:
      - SA_PASSWORD=Abc*123!
      - ACCEPT_EULA=Y
    volumes:
      - sqlserver-data:/var/opt/mssql
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
        order: start-first
      placement:
        constraints:
          - node.role == manager
    networks:
      - app-network

  frontenda:
    image: mangas330/frontenda
    ports:
    - target: 446
      published: 5010
      protocol: tcp
      mode: ingress
    volumes:
      - ./frontAdmin/ssl/server.crt:/etc/nginx/certs/server.crt
      - ./frontAdmin/ssl/server.key:/etc/nginx/certs/server.key
      - ./frontAdmin/ssl/nginx-default.conf:/etc/nginx/conf.d/default.conf
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    networks:
      - app-network

  frontendm:
    image: mangas330/frontendm
    ports:
    - target: 444
      published: 5011
      protocol: tcp
      mode: ingress
    volumes:
      - ./frontMedico/ssl/server.crt:/etc/nginx/certs/server.crt
      - ./frontMedico/ssl/server.key:/etc/nginx/certs/server.key
      - ./frontMedico/ssl/nginx-default.conf:/etc/nginx/conf.d/default.conf
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    networks:
      - app-network

  frontendc:
    image: mangas330/frontendc
    ports:
    - target: 445
      published: 5012
      protocol: tcp
      mode: ingress
    volumes:
      - ./frontCliente/ssl/server.crt:/etc/nginx/certs/server.crt
      - ./frontCliente/ssl/server.key:/etc/nginx/certs/server.key
      - ./frontCliente/ssl/nginx-default.conf:/etc/nginx/conf.d/default.conf
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    networks:
      - app-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
    - target: 5672
      published: 5672
      protocol: tcp
      mode: ingress
    - target: 15672
      published: 15672
      protocol: tcp
      mode: ingress
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
    networks:
      - app-network

networks:
  app-network:
    driver: overlay

volumes:
  sqlserver-data:
