services:
  pacientewebapi:
    image: mangas330/pacientewebapi
    build:
      context: .
      dockerfile: PacienteWebApi/Dockerfile
    ports:
      - 4999:8080
      - 5001:8081
    environment:
      - aspnetcore_environment=development
      - aspnetcore_http_ports=8080
      - aspnetcore_https_ports=8081
      - AES_KEY=${AES_KEY}
      - AES_IV=${AES_IV}
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}
    volumes:
      - ${appdata}/microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ${appdata}/asp.net/https:/home/app/.aspnet/https:ro
    container_name: PacienteWebApi_container
    depends_on:
      sqlserver:
        condition: service_healthy

  citasmedicaswebapi:
    image: mangas330/citasmedicaswebapi
    build:
      context: .
      dockerfile: CitaMedicaWebApi/Dockerfile
    ports:
      - 5002:8080
      - 5003:8081
    environment:
      - aspnetcore_environment=development
      - aspnetcore_http_ports=8080
      - aspnetcore_https_ports=8081
      - AES_KEY=${AES_KEY}
      - AES_IV=${AES_IV}
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}
    volumes:
      - ${appdata}/microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ${appdata}/asp.net/https:/home/app/.aspnet/https:ro
    container_name: CitasMedicasWebApi_container
    depends_on:
      sqlserver:
        condition: service_healthy

  historiaclinicawebapi:
    image: mangas330/historiaclinicawebapi
    build:
      context: .
      dockerfile: HistoriaClinicaWebApi/Dockerfile
    ports:
      - 5004:8080
      - 5005:8081
    environment:
      - aspnetcore_environment=development
      - aspnetcore_http_ports=8080
      - aspnetcore_https_ports=8081
      - AES_KEY=${AES_KEY}
      - AES_IV=${AES_IV}
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}
    volumes:
      - ${appdata}/microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ${appdata}/asp.net/https:/home/app/.aspnet/https:ro
    container_name: HistoriaClinicaWebApi_container
    depends_on:
      sqlserver:
        condition: service_healthy

  authwebapi:
    image: mangas330/authwebapi
    build:
      context: .
      dockerfile: AuthWebApi/Dockerfile
    ports:
      - 5006:8080
      - 5007:8081
    environment:
      - aspnetcore_environment=development
      - aspnetcore_http_ports=8080
      - aspnetcore_https_ports=8081
      - AES_KEY=${AES_KEY}
      - AES_IV=${AES_IV}
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}
    volumes:
      - ${appdata}/microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ${appdata}/asp.net/https:/home/app/.aspnet/https:ro
    container_name: AuthWebApi_container
    depends_on:
      sqlserver:
        condition: service_healthy

  administrativowebapi:
    image: mangas330/administrativowebapi
    build:
      context: .
      dockerfile: AdministrativoWebApi/Dockerfile
    ports:
      - 5008:8080
      - 5009:8081
    environment:
      - aspnetcore_environment=development
      - aspnetcore_http_ports=8080
      - aspnetcore_https_ports=8081
      - AES_KEY=${AES_KEY}
      - AES_IV=${AES_IV}
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}
    volumes:
      - ${appdata}/microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ${appdata}/asp.net/https:/home/app/.aspnet/https:ro
    container_name: AdministrativoWebApi_container
    depends_on:
      sqlserver:
        condition: service_healthy

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Abc*123!
      - ACCEPT_EULA=Y
    volumes:
      - sqlserver-data:/var/opt/mssql
    container_name: SQLServer_container
    healthcheck:
      test: ["CMD", "echo", "SQL Server is running"]
      interval: 1s
      timeout: 10s
      retries: 1

  nginx:
    image: mangas330/nginx
    build:
      context: .
      dockerfile: NginxDockerfile/Dockerfile
    container_name: nginx_container
    ports:
      - "443:443"
    volumes:
      - ./ssl/server.crt:/etc/nginx/certs/server.crt
      - ./ssl/server.key:/etc/nginx/certs/server.key
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - citasmedicaswebapi
      - pacientewebapi
      - historiaclinicawebapi
      - administrativowebapi
      
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
volumes:
  sqlserver-data:
