// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20241023151806_addEspecialidadMedicoTable")]
    partial class addEspecialidadMedicoTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Calendarios", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("CantidadCitas")
                        .HasColumnType("int");

                    b.Property<long>("ConsultorioId")
                        .HasColumnType("bigint");

                    b.Property<string>("DiasSemanaString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("EspecialidadId")
                        .HasColumnType("bigint");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.Property<long>("MedicoId")
                        .HasColumnType("bigint");

                    b.Property<int>("TiempoCita")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConsultorioId");

                    b.HasIndex("EspecialidadId");

                    b.HasIndex("MedicoId");

                    b.ToTable("Calendarios");
                });

            modelBuilder.Entity("DAL.Models.Articulos", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Articulos");
                });

            modelBuilder.Entity("DAL.Models.CitasMedicas", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CalendarioId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ConsultoriosId")
                        .HasColumnType("bigint");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<long?>("PacienteId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CalendarioId");

                    b.HasIndex("ConsultoriosId");

                    b.HasIndex("PacienteId");

                    b.ToTable("CitasMedicas");
                });

            modelBuilder.Entity("DAL.Models.ConsultasMedicas", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CitaMedicaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Diagnostico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CitaMedicaId")
                        .IsUnique();

                    b.ToTable("ConsultasMedicas");
                });

            modelBuilder.Entity("DAL.Models.Consultorios", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int>("Piso")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Consultorios");
                });

            modelBuilder.Entity("DAL.Models.Contratos", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<long>("PacienteId")
                        .HasColumnType("bigint");

                    b.Property<long>("SeguroMedicoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId")
                        .IsUnique();

                    b.HasIndex("SeguroMedicoId");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("DAL.Models.Copagos", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ArticuloId")
                        .HasColumnType("bigint");

                    b.Property<long>("EspecialidadId")
                        .HasColumnType("bigint");

                    b.Property<long>("SeguroMedicoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ArticuloId");

                    b.HasIndex("EspecialidadId");

                    b.HasIndex("SeguroMedicoId");

                    b.ToTable("Copagos");
                });

            modelBuilder.Entity("DAL.Models.Especialidades", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Especialidades");
                });

            modelBuilder.Entity("DAL.Models.EspecialidadesMedicos", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("EspecialidadId")
                        .HasColumnType("bigint");

                    b.Property<long>("MedicoId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("EspecialidadId");

                    b.HasIndex("MedicoId");

                    b.ToTable("EspecialidadesMedicos");
                });

            modelBuilder.Entity("DAL.Models.Estudios", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ConsultaMedicaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaRealizado")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaResultado")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaMedicaId");

                    b.ToTable("Estudios");
                });

            modelBuilder.Entity("DAL.Models.Facturas", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaPago")
                        .HasColumnType("datetime2");

                    b.Property<float>("Monto")
                        .HasColumnType("real");

                    b.Property<long>("PacienteId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Pago")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("DAL.Models.Medicos", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Medicos");
                });

            modelBuilder.Entity("DAL.Models.Notificaciones", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PacienteId")
                        .HasColumnType("bigint");

                    b.Property<bool>("Visto")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PacienteId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("DAL.Models.Pacientes", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly>("FechaDeNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Pacientes");
                });

            modelBuilder.Entity("DAL.Models.Precios", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("CopagoId")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<float>("PrecioBase")
                        .HasColumnType("real");

                    b.Property<long?>("SeguroMedicoId")
                        .IsRequired()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CopagoId");

                    b.HasIndex("SeguroMedicoId");

                    b.ToTable("Precios");
                });

            modelBuilder.Entity("DAL.Models.Recetas", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<long>("ConsultaMedicaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Frecuencia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreMedicamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("Vencimiento")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ConsultaMedicaId");

                    b.ToTable("Recetas");
                });

            modelBuilder.Entity("DAL.Models.SegurosMedicos", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SegurosMedicos");
                });

            modelBuilder.Entity("Calendarios", b =>
                {
                    b.HasOne("DAL.Models.Consultorios", "Consultorio")
                        .WithMany()
                        .HasForeignKey("ConsultorioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Especialidades", "Especialidad")
                        .WithMany("Calendarios")
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Medicos", "Medico")
                        .WithMany("Calendarios")
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultorio");

                    b.Navigation("Especialidad");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("DAL.Models.CitasMedicas", b =>
                {
                    b.HasOne("Calendarios", "Calendario")
                        .WithMany("CitasMedicas")
                        .HasForeignKey("CalendarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Consultorios", null)
                        .WithMany("CitasMedicas")
                        .HasForeignKey("ConsultoriosId");

                    b.HasOne("DAL.Models.Pacientes", "Paciente")
                        .WithMany("CitasMedicas")
                        .HasForeignKey("PacienteId");

                    b.Navigation("Calendario");

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("DAL.Models.ConsultasMedicas", b =>
                {
                    b.HasOne("DAL.Models.CitasMedicas", "CitaMedica")
                        .WithOne("ConsultaMedica")
                        .HasForeignKey("DAL.Models.ConsultasMedicas", "CitaMedicaId");

                    b.Navigation("CitaMedica");
                });

            modelBuilder.Entity("DAL.Models.Contratos", b =>
                {
                    b.HasOne("DAL.Models.Pacientes", "Paciente")
                        .WithOne("Contrato")
                        .HasForeignKey("DAL.Models.Contratos", "PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.SegurosMedicos", "SeguroMedico")
                        .WithMany("Contratos")
                        .HasForeignKey("SeguroMedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");

                    b.Navigation("SeguroMedico");
                });

            modelBuilder.Entity("DAL.Models.Copagos", b =>
                {
                    b.HasOne("DAL.Models.Articulos", "Articulo")
                        .WithMany("Copagos")
                        .HasForeignKey("ArticuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Especialidades", "Especialidad")
                        .WithMany("Copagos")
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.SegurosMedicos", "SeguroMedico")
                        .WithMany("Copagos")
                        .HasForeignKey("SeguroMedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Articulo");

                    b.Navigation("Especialidad");

                    b.Navigation("SeguroMedico");
                });

            modelBuilder.Entity("DAL.Models.EspecialidadesMedicos", b =>
                {
                    b.HasOne("DAL.Models.Especialidades", "Especialidad")
                        .WithMany()
                        .HasForeignKey("EspecialidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DAL.Models.Medicos", "Medico")
                        .WithMany()
                        .HasForeignKey("MedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Especialidad");

                    b.Navigation("Medico");
                });

            modelBuilder.Entity("DAL.Models.Estudios", b =>
                {
                    b.HasOne("DAL.Models.ConsultasMedicas", "ConsultaMedica")
                        .WithMany("Estudios")
                        .HasForeignKey("ConsultaMedicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsultaMedica");
                });

            modelBuilder.Entity("DAL.Models.Facturas", b =>
                {
                    b.HasOne("DAL.Models.Pacientes", "Paciente")
                        .WithMany("Facturas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("DAL.Models.Notificaciones", b =>
                {
                    b.HasOne("DAL.Models.Pacientes", "Paciente")
                        .WithMany("Notificaciones")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("DAL.Models.Precios", b =>
                {
                    b.HasOne("DAL.Models.Copagos", "Copago")
                        .WithMany("Precios")
                        .HasForeignKey("CopagoId");

                    b.HasOne("DAL.Models.SegurosMedicos", "SeguroMedico")
                        .WithMany("Precios")
                        .HasForeignKey("SeguroMedicoId");

                    b.Navigation("Copago");

                    b.Navigation("SeguroMedico");
                });

            modelBuilder.Entity("DAL.Models.Recetas", b =>
                {
                    b.HasOne("DAL.Models.ConsultasMedicas", "ConsultaMedica")
                        .WithMany("Recetas")
                        .HasForeignKey("ConsultaMedicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConsultaMedica");
                });

            modelBuilder.Entity("Calendarios", b =>
                {
                    b.Navigation("CitasMedicas");
                });

            modelBuilder.Entity("DAL.Models.Articulos", b =>
                {
                    b.Navigation("Copagos");
                });

            modelBuilder.Entity("DAL.Models.CitasMedicas", b =>
                {
                    b.Navigation("ConsultaMedica");
                });

            modelBuilder.Entity("DAL.Models.ConsultasMedicas", b =>
                {
                    b.Navigation("Estudios");

                    b.Navigation("Recetas");
                });

            modelBuilder.Entity("DAL.Models.Consultorios", b =>
                {
                    b.Navigation("CitasMedicas");
                });

            modelBuilder.Entity("DAL.Models.Copagos", b =>
                {
                    b.Navigation("Precios");
                });

            modelBuilder.Entity("DAL.Models.Especialidades", b =>
                {
                    b.Navigation("Calendarios");

                    b.Navigation("Copagos");
                });

            modelBuilder.Entity("DAL.Models.Medicos", b =>
                {
                    b.Navigation("Calendarios");
                });

            modelBuilder.Entity("DAL.Models.Pacientes", b =>
                {
                    b.Navigation("CitasMedicas");

                    b.Navigation("Contrato")
                        .IsRequired();

                    b.Navigation("Facturas");

                    b.Navigation("Notificaciones");
                });

            modelBuilder.Entity("DAL.Models.SegurosMedicos", b =>
                {
                    b.Navigation("Contratos");

                    b.Navigation("Copagos");

                    b.Navigation("Precios");
                });
#pragma warning restore 612, 618
        }
    }
}
